version: '3.8'  # A versão do Docker Compose que estamos usando.

services:
  web:
    build: .  # Diz ao Docker Compose para construir a imagem a partir do Dockerfile neste diretório.
    ports:
      - "5000:5000"  # Mapeia a porta 5000 da sua máquina (host) para a porta 5000 do container.
    volumes:
      - .:/app  # Opcional: monta o diretório atual da sua máquina no diretório /app do container.
                # Isso é ótimo para desenvolvimento, pois as mudanças no código local são refletidas no container sem precisar reconstruir a imagem.
    environment:
      FLASK_ENV: development  # Define uma variável de ambiente, útil para modo de desenvolvimento.