version: "3.8"

services:
  memcahed_python:
    build: .
    container_name: memcached_docker
    depends_on:
      - memcached
    environment:
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"